#! /usr/bin/env sh

# user-configured settings
TORI_ROOT="$HOME/.config/tori"

# global state
files=
base_files=
bkp_files=

# application logic

log() {
	local level="$1" # unimplemented
	local message="$2"

	if [ -n "$DEBUG" ] && [ $level = debug ]; then
		printf "$(date "+%H:%M:%N") $message\n"
	fi
}


scan_directory() {
	local target="$1"
	local files=
	local escaped_config_root="$(echo $TORI_ROOT | sed 's/\//\\\//g')"

	if [ -d "$target" ]; then
		scan="$(find "$target" -type f)"
		for line in $scan; do
			line="$(echo $line | sed "s/$escaped_config_root\///")"
			files="$line\n$files"
		done
	fi

	echo "$files"
}

base_files="$(scan_directory "$TORI_ROOT/base")"
bkp_files="$(scan_directory "$TORI_ROOT/bkp")"

log debug "collected base files:\n$base_files"
log debug "collected bkp files:\n$bkp_files"
