#! /usr/bin/env sh

main() {

  # paths
  VERSION="0.6.1 2025-01-02"
  TORI_ROOT="$HOME/.local/share/tori"
  CONFIG_ROOT="$HOME/.config/tori"
  BACKUP_ROOT="$HOME/.local/state/tori/backup"
  TMP_ROOT="/tmp/tori"
  CACHE_ROOT="$HOME/.cache/tori"

  # os-independent state
  DEBUG_DISABLED_WARNING=
  CANONICAL_OPTIONS='
  version:help:cache
  :check:only-files:only-packages:prefer-config:prefer-system
  '

  ## user input
  command="$1"
  user_options=

  # import source
  check_core_paths
  . "$TORI_ROOT/src/index.sh"

  ## os-dependent state
  set_opts on
  OS="$(get_operating_system)"
  PACKAGE_CACHE="$CACHE_ROOT/${OS}_packages.cache"
  AUTHORIZE_COMMAND="sudo"

  base_files=
  user_packages=
  system_packages=

  # startup checks
  prepare_directories

  # entry point
  user_options=$(parse_options "$*" "$CANONICAL_OPTIONS")
  log debug "[main] user_options = $user_options"

  case "$command" in
    check)
      check
      ;;
    cache)
      update_package_cache --force
      ;;
    version|-v|--version)
      echo "$VERSION"
      ;;
    help|-h|--help)
      print_help
      ;;
    *)
      echo "Use 'tori help' for usage instructions"
      ;;
  esac
}

check_core_paths() {
  local tori_conf="$CONFIG_ROOT/tori.conf"

  if [ -f "$tori_conf" ]; then
    local tori_root_value
    tori_root_value="$(grep -i '^tori_root' "$CONFIG_ROOT/tori.conf" \
      | cut -d '=' -f 2 | xargs \
      | sed "s*~*$HOME*" | sed "s*\$HOME*$HOME*g" \
    )"
    if [ -n "$tori_root_value" ]; then
      TORI_ROOT="$tori_root_value"
    fi
  fi

  if ! [ -f "$TORI_ROOT/src/index.sh" ]; then
    echo "No valid tori installation found at $TORI_ROOT"
    exit 1
  fi

}

main "$@"
