#! /usr/bin/env sh

VERSION="0.0.4 2024-06-30"
TORI_ROOT="$HOME/tori"
CONFIG_ROOT="$HOME/.config/tori"
TMP_DIR="/tmp/tori"

. "$TORI_ROOT/src/index.sh"

# state

## user input
argument="$1"
parameter="$2"

## global constants
OS="$(uname -s)"

## global state
base_files=
bkp_files=
user_packages=
system_packages=

# entry point

prepare_directories

if [ "$argument" = check ]; then
	check
elif [ "$argument" = version ] || [ "$argument" = -v ] || [ "$argument" = --version ]; then
	echo "$VERSION"
elif [ "$argument" = help ] || [ "$argument" = -h ] || [ "$argument" = --help ]; then
	print_help
else
	echo "Use 'tori help' for usage instructions"
fi
