#! /usr/bin/env sh

main() {
  # paths
  VERSION="0.0.4 2024-06-30"
  TORI_ROOT="$HOME/.local/share/tori"
  CONFIG_ROOT="$HOME/.config/tori"
  TMP_DIR="/tmp/tori"

  read_config_paths

  . "$TORI_ROOT/src/index.sh"

  # state

  DEBUG=$DEBUG

  ## user input
  argument="$1"
  parameter="$2"

  set_opts -

  ## global constants
  OS="$(get_operating_system)"

  ## global state
  base_files=
  bkp_files=
  user_packages=
  system_packages=

  # entry point

  prepare_directories

  if [ "$argument" = check ]; then
    check
  elif [ "$argument" = version ] || [ "$argument" = -v ] || [ "$argument" = --version ]; then
    echo "$VERSION"
  elif [ "$argument" = help ] || [ "$argument" = -h ] || [ "$argument" = --help ]; then
    print_help
  else
    echo "Use 'tori help' for usage instructions"
  fi
}

read_config_paths() {
  TORI_ROOT="$(grep -i '^tori_root' "$CONFIG_ROOT/tori.conf" \
    | cut -d '=' -f 2 | xargs \
    | sed "s*~*$HOME*" | sed "s*\$HOME*$HOME*g" \
  )"
  [ -n "$DEBUG" ] && echo "TORI_ROOT: $TORI_ROOT"
}

main "$1" "$2"
